/** Declaration file generated by dts-gen */
declare module "ml-knn";

declare class KNN {
    constructor(...args: any[]);

    predict(...args: any[]): any;

    toJSON(...args: any[]): any;

    static load(...args: any[]): any;
}
