/** Declaration file generated by dts-gen */

declare module 'ml-logistic-regression';

declare class LogisticRegression {
    constructor(...args: any[]);

    predict(...args: any[]): any;

    toJSON(...args: any[]): any;

    train(...args: any[]): any;

    static load(...args: any[]): any;

}

export = LogisticRegression;