/** Declaration file generated by dts-gen */

declare module "ml-random-forest";

declare class RandomForestClassifier {
    constructor(...args: any[]);

    selection(...args: any[]): any;

    train(...args: any[]): any;

    predict(...args: any[]): any;

    toJSON(...args: any[]): any;

    static load(...args: any[]): any;
}

declare class RandomForestRegression {
    constructor(...args: any[]);

    selection(...args: any[]): any;

    train(...args: any[]): any;

    predict(...args: any[]): any;

    toJSON(...args: any[]): any;

    static load(...args: any[]): any;
}
