query GetEditorProjectDetails($id: String!) {
    project(id: $id) {
        id
        userId
        user {
            id
            name
        }
        name
        isPublic
        summary
        description
        projectJson
        modelsDb
    }
}
