query GetEditorProjectDetails($id: String!) {
    project(id: $id) {
        userId,
        user {
            name
        },
        name,
        isPublic,
        description,
        projectJson
    }
}