query GetProjectDetailsUserProjects($userId: String!) {
    projects(user: $userId, sortByNewest: true, take: 4, isPublic: true) {
        id
        name
        description
        updatedAt
        isPublic
    }
}
