query GetProjectDetails($id: String!) {
    project(id: $id) {
        ...ProjectDetails
    }
}

fragment ProjectDetails on Project {
    id
    createdAt
    updatedAt
    userId
    user {
        name
        projects(sortByNewest: true, take: 4, isPublic: true) {
            id
            name
            description
            updatedAt
            isPublic
        }
    }
    name
    isPublic
    description
    summary
    parent {
        id
        name
        userId
        user {
            name
        }
    }
    children(sortByNewest: true, isPublic: true) {
        id
    }
}
