query GetRecentProjects {
    projects(sortByNewest: true, isPublic: true) {
        ...UserProjectCard
    }
}

fragment UserProjectCard on Project {
    id
    updatedAt
    name
    summary
    isPublic
    user {
        name
    }
}
