query GetUserProjects($user: String!) {
    projects(user: $user, sortByNewest: true) {
        ...UserProject
    }
}

# If you update this, update the list of fields in apolloClient.ts (around line 39)
fragment UserProject on Project {
    id
    name
    isPublic
    summary
    updatedAt
    userId
}
