query GetUserProjects($user: String!) {
    projects(user: $user, sortByNewest: true) {
        ...UserProject
    }
}

fragment UserProject on Project {
    id
    name
    isPublic
    summary
    updatedAt
}
