mutation SaveProject($id: String!, $projectJson: String!, $modelsDb: String) {
    editProject(id: $id, projectJson: $projectJson, modelsDb: $modelsDb) {
        id
        projectJson
        modelsDb
        updatedAt
    }
}
